### ISSUE TITLE
标签页

### ISSUE THREAD

**Issue by moyels** [imhanjie/gridea-theme-pure#10]
当标签页一行内无法展示所有的标签时，会出现一个很影响体验的问题，标签并不会换行，而且超出了页面之外。
使用flex布局解决了这个问题，希望下个版本可以修复。
```css
div.tags-container {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
    align-items: center;
}
```
