### ISSUE TITLE
想添加两个功能

### ISSUE THREAD

**Issue by Phoenix-Pl** [imhanjie/gridea-theme-pure#42]
请问大佬还更新吗，想要一个文章内部目录和回到顶部的功能

**Comment by jxiaow** [comment]
@Thronepeter 我这边fork了作者的源码自行修改了一下，能满足你的一部分需求[https://github.com/jxiaow/gridea-theme-pure-fashion](https://github.com/jxiaow/gridea-theme-pure-fashion)

**Comment by renbaoshuo** [comment]
在 `post.ejs` 的合适位置插入以下代码：
```ejs
<% if (post.toc) { %>
    <div class="post-toc">
        <h2 id="目录">目录</h2>
        <%- post.toc %>
    </div>
    <hr>
<% } %>
```

并在 `post.less` 的合适位置插入以下代码：
```less
.post-toc {
    margin-bottom: 30px;

    h2 {
        display: inline-block;
        background: linear-gradient(180deg, transparent 75%, rgba(139, 149, 159, 0.4) 0) !important;
    }

    ul {
        margin: 0px;
    }

    .markdownIt-TOC {
        padding: 0px;

        li {
            list-style: none;
            margin: 0px;

            ul li {
                list-style-type: disc;
                margin: 0px;

                a {
                    color: var(--content-first) !important;
                }
            }
        }
    }
}
```


效果类似于这样：[线段树学习笔记 - 宝硕博客 (web.archive.org)](https://web.archive.org/web/20210131143222/https://blog.baoshuo.ren/post/segment-tree-note/#%E7%9B%AE%E5%BD%95)

![image](https://user-images.githubusercontent.com/47095648/106415158-59833400-6489-11eb-9991-da4460775523.png)
